services:
  postgres:
    image: postgres:15-alpine
    container_name: store-postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Dev2024full
      POSTGRES_DB: store_db
    ports:
      - "5432:5432"
